# -*- coding: utf-8 -*-
"""Fooocus AI Image Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EyYetF6VB1ZHwzcuy_vDmqnywOPVUTlK
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install pygit2==1.12.2
# %cd /content
!git clone https://github.com/lllyasviel/Fooocus.git
# %cd /content/Fooocus
!python entry_with_update.py --share --always-high-vram